name: Makefile-CI-dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version: '1.21.x'

    - name: Run tests
      run: make test

    - name: Run code coverage
      run: make cover

    - name: Upload code coverage file
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-html-file
        path: ./out/var/coverage.html
